name: cat_trivia
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  logger: any
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.5
  # Services
  path_provider:
  hive: ^2.2.3
  retrofit: '>=3.0.0 <4.0.0'
  # API
  http:
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: '>=4.0.0 <5.0.0'
  json_serializable: '>4.4.0'
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/



  fonts:
    - family: TTNorms-Bold
      fonts:
        - asset: assets/fonts/TTNorms-Bold.ttf
